version: "3.0"
services:
  weather-app1:
    container_name: weather-app1
    build:
      context: ./weather-app
      args:
      - VERSION="v2.0"
    environment:
    - NODE_ENV="production"
    ports:
    - "8080:3000"
    networks:
    - weather-app

  weather-app2:
    container_name: weather-app2
    build:
      context: ./weather-app
      args:
      - VERSION="v2.0"
    environment:
    - NODE_ENV="production"
    ports:
    - "8081:3000"
    networks:
    - weather-app

  weather-app3:
    container_name: weather-app3
    build:
      context: ./weather-app
      args:
      - VERSION="v2.0"
    environment:
    - NODE_ENV="production"
    ports:
    - "8082:3000"
    networks:
    - weather-app

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    tty: true
    ports:
    - "80:80"
    networks:
    - frontend
    - weather-app

networks:
  frontend:
    internal: true
  weather-app:
